# /*
#   Command Format:
#       Send Command        --> [COMMAND_HEADER:u8] [OP_CODE:u8] [PARAMETER]
#       Response Command    --> [COMMAND_HEADER:u8] [ERROR_CODE:u8] [OP_CODE:u8] [RESPONSE_MESSAGE]
#
#   Event Format:
#       Received Event      --> [EVENT_HEADER:u8] [EVENT_CODE:u8] [MOTOR_ID:u8]
#
#   Logger Format:
#       Received Log Data   --> [LOGGER_HEADER:u8] [sequence:u8] [time_stamp:u32] [DATA_LOG:[i32;5]]
#           DATA_LOG:[i32;5] =  [current_pos, current_speed, commanded_pos, commanded_speed, commanded_pwm]
# */

# ---------------------------------- Project -----------------------------------#
[project]
description = "RP2040 DC Motor Control"
name        = "DCMotor"
version     = "0.2.1"

# ---------------------------------- Headers -----------------------------------#
[headers]
COMMAND = 0xFF
EVENT   = 0xFE
LOGGER  = 0xFD

# ---------------------------------- ENUMS -----------------------------------#
[enums.EventCodes]
0 = "MOVE_MOTOR_DONE"

[enums.ErrorCodes]
0 = "NoError"
1 = "OpCodeNotFound"
2 = "NonFiniteFloat"
3 = "ReadByteError"
4 = "InvalidMotorId"
5 = "InvalidHeaderCode"
6 = "InvalidTimeSampling"
7 = "FlashStorageError"
8 = "ZeroDivisionError"

[telemetry]
flags = [
    { name = "MotorPosition", label = "Motor_Position(rotation)", scale = "1.0 / (4.4 * 11.0)", offset = "0.0" },
    { name = "MotorSpeed", label = "Motor_Speed(RPM)", scale = "60.0 / (4.4 * 11.0)", offset = "0.0" },
    { name = "CommandedPosition", label = "Commanded_Position(rotation)", scale = "1.0 / (4.4 * 11.0)", offset = "0.0" },
    { name = "CommandedSpeed", label = "Commanded_Speed(RPM)", scale = "60.0 / (4.4 * 11.0)", offset = "0.0" },
    { name = "CommandedPwm", label = "Commanded_PWM", scale = "1.0", offset = "0.0" },
]

# ---------------------------------- Firmware Logger ----------------------------------#
[[commands]]
args    = { motor_id = "u8", time_sampling = "u64" }
command = "start_logger"
desc    = "Start the firmware logger by set the time sampling in ms (min 1 ms)"
op      = 1
ret     = {}

[[commands]]
args    = { motor_id = "u8" }
command = "stop_logger"
desc    = "Stop the firmware logger"
op      = 2
ret     = {}

# -------------------------------- Motor Config ---------------------------------#
[[commands]]
args    = { motor_id = "u8", kp = "f32", ki = "f32", kd = "f32", i_limit = "f32" }
command = "set_pid_motor_pos"
desc    = "Set Motor PID parameters for Position Control"
op      = 6
ret     = {}

[[commands]]
args    = { motor_id = "u8", kp = "f32", ki = "f32", kd = "f32", i_limit = "f32" }
command = "set_pid_motor_speed"
desc    = "Set Motor PID parameters for Speed Control"
op      = 8
ret     = {}

[[commands]]
args    = { motor_id = "u8" }
command = "get_pid_motor_pos"
desc    = "Get motor position PID parameter(s)"
op      = 7
ret     = { kp = "f32", ki = "f32", kd = "f32", i_limit = "f32" }

[[commands]]
args    = { motor_id = "u8" }
command = "get_pid_motor_speed"
desc    = "Get motor speed PID parameter(s)"
op      = 9
ret     = { kp = "f32", ki = "f32", kd = "f32", i_limit = "f32" }

# --------------------------------- Move Motor ----------------------------------#
[[commands]]
args    = { motor_id = "u8", vel = "i32" }
command = "move_motor_speed"
desc    = "Motor Speed Control with Step Motion Profile in count per second (cps)"
op      = 3
ret     = {}

[[commands]]
args    = { motor_id = "u8", target = "i32" }
command = "move_motor_abs_pos"
desc    = "Motor Position Control with Step Motion Profile in count"
op      = 4
ret     = {}

[[commands]]
args = { motor_id = "u8", target = "i32", vel = "i32", acc = "i32" }
command = "move_motor_abs_pos_trapezoid"
desc = """
            Motor Position Control with Commanded Trapezoid Motion Profile
            Argument(s)
            - target: Position Target in Count
            - vel: Commanded Velocity in Count per Second (cps)
            - acc: Commanded Acceleration in Count per Second Square (cps^2)
        """
op = 10
ret = {}

[[commands]]
args = { motor_id = "u8", pwm = "i32" }
command = "move_motor_open_loop"
desc = """
            Motor Speed Control with Open Loop Mode
            Argument(s)
            - pwm: pwm duty cycle from 0 - 1000
        """
op = 13
ret = {}

[[commands]]
args    = { motor_id = "u8" }
command = "stop_motor"
desc    = "Stop the motor"
op      = 5
ret     = {}

[[commands]]
args    = { motor_id = "u8" }
command = "get_motor_pos"
desc    = "Get motor position in Count"
op      = 11
ret     = { pos_count = "i32" }

[[commands]]
args    = { motor_id = "u8" }
command = "get_motor_speed"
desc    = "Get motor speed in Count per Second (cps)"
op      = 12
ret     = { speed_cps = "i32" }

[[commands]]
args    = {}
command = "save_configuration"
desc    = "save PID parameter on the Flash memory"
op      = 14
ret     = {}

[[commands]]
args    = {}
command = "reset_configuration"
desc    = "reset PID parameter to default configuration"
op      = 15
ret     = {}

[[commands]]
args    = {}
command = "get_firmware_version"
desc    = "Get the compiled firmware version components (Major, Minor, Patch)"
op      = 16
ret     = { major = "u8", minor = "u8", patch = "u8" }

[[commands]]
args    = { motor_id = "u8" }
command = "get_motor_max_speed"
desc    = "Get the motor maximum speed in cps"
op      = 17
ret     = { motor_max_speed_cps = "i32" }

[[commands]]
args    = { motor_id = "u8", motor_max_speed_cps = "i32" }
command = "set_motor_max_speed"
desc    = "Set the motor maximum speed in cps"
op      = 18
ret     = {}
