[target.'cfg(all(target_arch = "arm", target_os = "none"))']
runner = "probe-rs run --chip RP2040"

rustflags = [
    "-C",
    "linker=flip-link", # Highly recommended for stack overflow protection
]

[build]
target = "thumbv6m-none-eabi" # Cortex-M0 and Cortex-M0+

[env]
DEFMT_LOG = "debug"

[alias]
run-uf2 = [
    "run",
    "--config",
    "target.'cfg(all(target_arch = \"arm\", target_os = \"none\"))'.runner=\"elf2uf2-rs\"",
    "--release",
    "--package",
]
